<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Parentee_BE.BLL</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Parentee_BE.DAL\Parentee_BE.DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
      <PackageReference Include="PhoneNumbersCore" Version="1.1.1" />
      <PackageReference Include="StackExchange.Redis" Version="2.9.11" />
      <PackageReference Include="Twilio" Version="7.12.2" />
    </ItemGroup>

</Project>
