// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parentee_BE.DAL.Context;

#nullable disable

namespace Parentee_BE.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017000344_AddGenderForUserEntity")]
    partial class AddGenderForUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_log_pkey");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.AuthIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUid")
                        .HasColumnType("text")
                        .HasColumnName("provider_uid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("auth_identity_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Provider", "ProviderUid" }, "auth_identity_provider_provider_uid_key")
                        .IsUnique();

                    b.ToTable("auth_identity");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.CalendarEventEntity", b =>
                {
                    b.Property<bool?>("AllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("all_day");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EventEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_end");

                    b.Property<DateTime?>("EventStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_start");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.ToTable((string)null);

                    b.ToView("calendar_event", (string)null);
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PhotoImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_image_id");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("child_pkey");

                    b.HasIndex("PhotoImageId");

                    b.HasIndex(new[] { "FamilyId" }, "idx_child_family");

                    b.ToTable("child");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildPhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.HasKey("Id")
                        .HasName("child_photo_pkey");

                    b.HasIndex("ChildId");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("IX_child_photo_image_id1");

                    b.ToTable("child_photo");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildVaccinationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AdministeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("administered_at");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomName")
                        .HasColumnType("text")
                        .HasColumnName("custom_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("VaccineId")
                        .HasColumnType("uuid")
                        .HasColumnName("vaccine_id");

                    b.HasKey("Id")
                        .HasName("child_vaccination_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("VaccineId");

                    b.HasIndex(new[] { "ChildId", "ScheduledAt" }, "idx_child_vacc_sched");

                    b.ToTable("child_vaccination");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.DiaperChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool?>("RashObserved")
                        .HasColumnType("boolean")
                        .HasColumnName("rash_observed");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("diaper_change_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyId");

                    b.HasIndex(new[] { "ChildId", "ChangedAt" }, "idx_diaper_child_time")
                        .IsDescending(false, true);

                    b.ToTable("diaper_change");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.EntitlementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entitlement_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex(new[] { "FamilyId", "ProductId", "StartsAt" }, "entitlement_family_id_product_id_starts_at_key")
                        .IsUnique();

                    b.ToTable("entitlement");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.FamilyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_image_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("family_pkey");

                    b.HasIndex("CoverImageId");

                    b.ToTable("family");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.FeedingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AmountMl")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("amount_ml");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("duration_min");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Side")
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("feeding_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyId");

                    b.HasIndex(new[] { "ChildId", "StartedAt" }, "idx_feeding_child_time")
                        .IsDescending(false, true);

                    b.ToTable("feeding");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("image_pkey");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex(new[] { "FamilyId" }, "idx_image_family");

                    b.ToTable("image");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AmountTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_total");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("citext")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerTaxCode")
                        .HasColumnType("text")
                        .HasColumnName("buyer_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::text");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("text")
                        .HasColumnName("invoice_no");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("PdfImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("pdf_image_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.HasKey("Id")
                        .HasName("invoice_pkey");

                    b.HasIndex("PdfImageId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex(new[] { "InvoiceNo" }, "invoice_invoice_no_key")
                        .IsUnique();

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.MeasurementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Value")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("measurement_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyId");

                    b.HasIndex(new[] { "ChildId", "MeasuredAt" }, "idx_measurement_child_time")
                        .IsDescending(false, true);

                    b.ToTable("measurement");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.NotificationOutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notification_outbox_pkey");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("notification_outbox");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.PriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProviderPriceId")
                        .HasColumnType("text")
                        .HasColumnName("provider_price_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("price_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("price");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("product_pkey");

                    b.HasIndex(new[] { "Code" }, "product_code_key")
                        .IsUnique();

                    b.ToTable("product");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.PurchaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("CreditCard")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProviderTxnId")
                        .HasColumnType("text")
                        .HasColumnName("provider_txn_id");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("purchase_pkey");

                    b.HasIndex("FamilyId");

                    b.HasIndex("PriceId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("purchase");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.RefundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::text");

                    b.Property<string>("ProviderRefundId")
                        .HasColumnType("text")
                        .HasColumnName("provider_refund_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RefundedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("refund_pkey");

                    b.HasIndex("PurchaseId");

                    b.ToTable("refund");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ReminderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Push")
                        .HasColumnName("channel");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remind_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("reminder_pkey");

                    b.HasIndex("TaskId");

                    b.ToTable("reminder");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.SleepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMin")
                        .HasColumnType("integer")
                        .HasColumnName("duration_min");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("sleep_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FamilyId");

                    b.HasIndex(new[] { "ChildId", "StartedAt" }, "idx_sleep_child_time")
                        .IsDescending(false, true);

                    b.ToTable("sleep");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AllDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("all_day");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("task_pkey");

                    b.HasIndex("ChildId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "FamilyId", "StartsAt" }, "idx_task_family_time");

                    b.ToTable("task");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.TaskRecurrenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.HasKey("Id")
                        .HasName("task_recurrence_pkey");

                    b.HasIndex("TaskId");

                    b.ToTable("task_recurrence");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AvatarImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_image_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("SigninMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signup_method");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex("AvatarImageId");

                    b.HasIndex(new[] { "Email" }, "user_email_key")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.UserFamilyRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_family_role_pkey");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "FamilyId" }, "user_family_role_user_id_family_id_key")
                        .IsUnique();

                    b.ToTable("user_family_role");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.VaccineCatalogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Doses")
                        .HasColumnType("integer")
                        .HasColumnName("doses");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RecommendedAgeDays")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_age_days");

                    b.HasKey("Id")
                        .HasName("vaccine_catalog_pkey");

                    b.HasIndex(new[] { "Code" }, "vaccine_catalog_code_key")
                        .IsUnique();

                    b.ToTable("vaccine_catalog");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("AuditLogs")
                        .HasForeignKey("FamilyId")
                        .HasConstraintName("audit_log_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("audit_log_user_id_fkey");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.AuthIdentityEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("auth_identity_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Children")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("child_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.ImageEntity", "PhotoImage")
                        .WithMany("Children")
                        .HasForeignKey("PhotoImageId")
                        .HasConstraintName("child_photo_image_id_fkey");

                    b.Navigation("Family");

                    b.Navigation("PhotoImage");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildPhotoEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("ChildPhotos")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("child_photo_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.ImageEntity", "Image")
                        .WithMany("ChildPhotos")
                        .HasForeignKey("ImageId")
                        .IsRequired()
                        .HasConstraintName("child_photo_image_id_fkey1");

                    b.Navigation("Child");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildVaccinationEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("ChildVaccinations")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("child_vaccination_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "CreatedByNavigation")
                        .WithMany("ChildVaccinationCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("child_vaccination_created_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("ChildVaccinations")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("child_vaccination_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "UpdatedByNavigation")
                        .WithMany("ChildVaccinationUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("child_vaccination_updated_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.VaccineCatalogEntity", "Vaccine")
                        .WithMany("ChildVaccinations")
                        .HasForeignKey("VaccineId")
                        .HasConstraintName("child_vaccination_vaccine_id_fkey");

                    b.Navigation("Child");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Family");

                    b.Navigation("UpdatedByNavigation");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.DiaperChangeEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("DiaperChanges")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("diaper_change_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "CreatedByNavigation")
                        .WithMany("DiaperChanges")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("diaper_change_created_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("DiaperChanges")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("diaper_change_family_id_fkey");

                    b.Navigation("Child");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.EntitlementEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Entitlements")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("entitlement_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.ProductEntity", "Product")
                        .WithMany("Entitlements")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("entitlement_product_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.PurchaseEntity", "Purchase")
                        .WithMany("Entitlements")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("entitlement_purchase_id_fkey");

                    b.Navigation("Family");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.FamilyEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ImageEntity", "CoverImage")
                        .WithMany("Families")
                        .HasForeignKey("CoverImageId")
                        .HasConstraintName("family_cover_image_id_fkey");

                    b.Navigation("CoverImage");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.FeedingEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("Feedings")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("feeding_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "CreatedByNavigation")
                        .WithMany("Feedings")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("feeding_created_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Feedings")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("feeding_family_id_fkey");

                    b.Navigation("Child");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ImageEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Images")
                        .HasForeignKey("FamilyId")
                        .HasConstraintName("fk_image_family");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "OwnerUser")
                        .WithMany("Images")
                        .HasForeignKey("OwnerUserId")
                        .HasConstraintName("fk_image_owner");

                    b.Navigation("Family");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ImageEntity", "PdfImage")
                        .WithMany("Invoices")
                        .HasForeignKey("PdfImageId")
                        .HasConstraintName("invoice_pdf_image_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.PurchaseEntity", "Purchase")
                        .WithMany("Invoices")
                        .HasForeignKey("PurchaseId")
                        .IsRequired()
                        .HasConstraintName("invoice_purchase_id_fkey");

                    b.Navigation("PdfImage");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.MeasurementEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("Measurements")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("measurement_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "CreatedByNavigation")
                        .WithMany("Measurements")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("measurement_created_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Measurements")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("measurement_family_id_fkey");

                    b.Navigation("Child");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.NotificationOutboxEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("NotificationOutboxes")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("notification_outbox_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "User")
                        .WithMany("NotificationOutboxes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("notification_outbox_user_id_fkey");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.PriceEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ProductEntity", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("price_product_id_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.PurchaseEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Purchases")
                        .HasForeignKey("FamilyId")
                        .HasConstraintName("purchase_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.PriceEntity", "Price")
                        .WithMany("Purchases")
                        .HasForeignKey("PriceId")
                        .HasConstraintName("purchase_price_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.ProductEntity", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("purchase_product_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("purchase_user_id_fkey");

                    b.Navigation("Family");

                    b.Navigation("Price");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.RefundEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.PurchaseEntity", "Purchase")
                        .WithMany("Refunds")
                        .HasForeignKey("PurchaseId")
                        .IsRequired()
                        .HasConstraintName("refund_purchase_id_fkey");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ReminderEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.TaskEntity", "Task")
                        .WithMany("Reminders")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reminder_task_id_fkey");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.SleepEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("Sleeps")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("sleep_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "CreatedByNavigation")
                        .WithMany("Sleeps")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("sleep_created_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Sleeps")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("sleep_family_id_fkey");

                    b.Navigation("Child");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.TaskEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ChildEntity", "Child")
                        .WithMany("Tasks")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("task_child_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "CreatedByNavigation")
                        .WithMany("TaskCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("task_created_by_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Tasks")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("task_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "UpdatedByNavigation")
                        .WithMany("TaskUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("task_updated_by_fkey");

                    b.Navigation("Child");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Family");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.TaskRecurrenceEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.TaskEntity", "Task")
                        .WithMany("TaskRecurrences")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("task_recurrence_task_id_fkey");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.ImageEntity", "AvatarImage")
                        .WithMany("Users")
                        .HasForeignKey("AvatarImageId")
                        .HasConstraintName("user_avatar_image_id_fkey");

                    b.Navigation("AvatarImage");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.UserFamilyRoleEntity", b =>
                {
                    b.HasOne("Parentee_BE.DAL.Data.Entities.FamilyEntity", "Family")
                        .WithMany("UserFamilyRoles")
                        .HasForeignKey("FamilyId")
                        .IsRequired()
                        .HasConstraintName("user_family_role_family_id_fkey");

                    b.HasOne("Parentee_BE.DAL.Data.Entities.UserEntity", "User")
                        .WithOne("UserFamilyRole")
                        .HasForeignKey("Parentee_BE.DAL.Data.Entities.UserFamilyRoleEntity", "UserId")
                        .IsRequired()
                        .HasConstraintName("user_family_role_user_id_fkey");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ChildEntity", b =>
                {
                    b.Navigation("ChildPhotos");

                    b.Navigation("ChildVaccinations");

                    b.Navigation("DiaperChanges");

                    b.Navigation("Feedings");

                    b.Navigation("Measurements");

                    b.Navigation("Sleeps");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.FamilyEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ChildVaccinations");

                    b.Navigation("Children");

                    b.Navigation("DiaperChanges");

                    b.Navigation("Entitlements");

                    b.Navigation("Feedings");

                    b.Navigation("Images");

                    b.Navigation("Measurements");

                    b.Navigation("NotificationOutboxes");

                    b.Navigation("Purchases");

                    b.Navigation("Sleeps");

                    b.Navigation("Tasks");

                    b.Navigation("UserFamilyRoles");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ImageEntity", b =>
                {
                    b.Navigation("ChildPhotos");

                    b.Navigation("Children");

                    b.Navigation("Families");

                    b.Navigation("Invoices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.PriceEntity", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.ProductEntity", b =>
                {
                    b.Navigation("Entitlements");

                    b.Navigation("Prices");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.PurchaseEntity", b =>
                {
                    b.Navigation("Entitlements");

                    b.Navigation("Invoices");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.TaskEntity", b =>
                {
                    b.Navigation("Reminders");

                    b.Navigation("TaskRecurrences");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("AuthIdentities");

                    b.Navigation("ChildVaccinationCreatedByNavigations");

                    b.Navigation("ChildVaccinationUpdatedByNavigations");

                    b.Navigation("DiaperChanges");

                    b.Navigation("Feedings");

                    b.Navigation("Images");

                    b.Navigation("Measurements");

                    b.Navigation("NotificationOutboxes");

                    b.Navigation("Purchases");

                    b.Navigation("Sleeps");

                    b.Navigation("TaskCreatedByNavigations");

                    b.Navigation("TaskUpdatedByNavigations");

                    b.Navigation("UserFamilyRole");
                });

            modelBuilder.Entity("Parentee_BE.DAL.Data.Entities.VaccineCatalogEntity", b =>
                {
                    b.Navigation("ChildVaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
